import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FileText, RefreshCw, Copy } from "lucide-react";
import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

interface CounterNarrativeStatementProps {
  brandName: string;
  keywords: Array<{ word: string; count: number }>;
  sentimentDistribution: { positive: number; neutral: number; negative: number };
  threatLevel: "low" | "medium" | "high" | "critical";
}

export function CounterNarrativeStatement({
  brandName,
  keywords,
  sentimentDistribution,
  threatLevel,
}: CounterNarrativeStatementProps) {
  const [statement, setStatement] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();

  const generateStatement = async () => {
    setLoading(true);
    try {
      const topTopics = keywords.slice(0, 5).map(k => k.word).join(", ");
      const sentimentSummary = `${sentimentDistribution.positive}% positive, ${sentimentDistribution.neutral}% neutral, ${sentimentDistribution.negative}% negative`;

      const { data, error } = await supabase.functions.invoke('generate-counter-narrative', {
        body: {
          brand: brandName,
          topTopics,
          sentimentSummary,
          riskLevel: threatLevel,
        }
      });

      if (error) throw error;
      
      if (data?.statement) {
        setStatement(data.statement);
      }
    } catch (error: any) {
      console.error('Error generating statement:', error);
      toast({
        title: "Error",
        description: error.message || "Failed to generate statement",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    generateStatement();
  }, [brandName, threatLevel]);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(statement);
    toast({
      title: "Copied",
      description: "Statement copied to clipboard",
    });
  };

  return (
    <Card className="animate-fade-in border-4 border-border">
      <CardHeader className="border-b-4 border-border bg-secondary">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="uppercase tracking-wider flex items-center gap-2">
              <FileText className="h-5 w-5" />
              Suggested Counter-Narrative Statement
            </CardTitle>
          </div>
          <div className="flex gap-2">
            {statement && (
              <Button
                onClick={copyToClipboard}
                variant="outline"
                size="sm"
                className="gap-2"
              >
                <Copy className="h-4 w-4" />
                Copy
              </Button>
            )}
            <Button
              onClick={generateStatement}
              disabled={loading}
              variant="outline"
              size="sm"
              className="gap-2"
            >
              <RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
              Regenerate
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="pt-6">
        {loading ? (
          <div className="flex items-center justify-center py-8">
            <div className="animate-pulse text-muted-foreground">Drafting statement...</div>
          </div>
        ) : statement ? (
          <div className="animate-fade-in">
            <div className="p-6 border-2 border-primary bg-primary/5 rounded-lg">
              <p className="text-foreground leading-relaxed whitespace-pre-wrap">
                {statement}
              </p>
            </div>
            <p className="text-xs text-muted-foreground mt-4 italic">
              Draft generated by 808080 – Grey Zone Narrative Intelligence. Review before publication.
            </p>
          </div>
        ) : (
          <div className="text-center text-muted-foreground py-8">
            No statement generated yet
          </div>
        )}
      </CardContent>
    </Card>
  );
}
